version: "2.3"
services:
  docs:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm start
    volumes:
      - ./:/api-docs
      - /api-docs/node_modules
    tty: true
    stdin_open: true